FROM node:20-alpine 

WORKDIR /anokha

COPY . .

# Set environment variables needed for build
ARG NEXT_PUBLIC_IS_PRODUCTION
ARG NEXT_PUBLIC_PAY_U_KEY_TEST
ARG NEXT_PUBLIC_PAY_U_KEY_PROD

ENV NEXT_PUBLIC_IS_PRODUCTION=${NEXT_PUBLIC_IS_PRODUCTION}
ENV NEXT_PUBLIC_PAY_U_KEY_TEST=${NEXT_PUBLIC_PAY_U_KEY_TEST}
ENV NEXT_PUBLIC_PAY_U_KEY_PROD=${NEXT_PUBLIC_PAY_U_KEY_PROD}

RUN npm i --force

EXPOSE 3002

RUN npm run build

CMD ["npm","run","start"]
